M48
; DRILL file KiCad 10.0.2 date 2026-06-05T21:48:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-05T21:48:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.8368Y-4.0201
X4.8368Y-4.2476
T2
X4.8622Y-4.5177
X5.0886Y-3.75
X6.8996Y-4.5866
M30
