M48
; DRILL file KiCad 10.0.3 date 2026-05-29T12:35:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-29T12:35:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X8.0061Y-3.7346
X8.0061Y-3.9622
T2
X8.1388Y-3.5522
X8.9075Y-4.4094
X9.626Y-3.9173
M30
